# Generated by Django 5.2.17 on 2026-08-14 18:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(help_text='translation|embedding|chat', max_length=32)),
                ('provider', models.CharField(help_text='selfhosted|deepl|openai|anthropic', max_length=32)),
                ('pii_filtered', models.BooleanField(default=False, help_text='Guardrail ran and passed')),
                ('chars_in', models.PositiveIntegerField(default=0)),
                ('chars_out', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='ok', help_text='ok|failed|blocked', max_length=16)),
            ],
            options={
                'indexes': [models.Index(fields=['purpose', 'created_at'], name='ai_service__purpose_22f1f7_idx')],
            },
        ),
    ]
