# Generated by Django 5.2.17 on 2026-08-14 18:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='pending', help_text='pending|ready|expired', max_length=16)),
                ('file_key', models.CharField(blank=True, default='', help_text='S3 key; signed URL on demand', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ErasureRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('in_progress', 'Fan-out in progress'), ('completed', 'Completed'), ('partially_blocked', 'Blocked by retention obligations')], default='requested', max_length=24)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('receipt', models.JSONField(default=dict, help_text='Per-handler outcomes — the erasure evidence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_id', models.UUIDField(blank=True, help_text='Null = system actor', null=True)),
                ('action', models.CharField(max_length=64)),
                ('target_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['action', 'created_at'], name='compliance__action_71626d_idx')],
            },
        ),
    ]
