# Generated by Django 5.2.17 on 2026-09-02 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='dataexport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='erasurerequest',
            options={'ordering': ['-created_at']},
        ),
    ]
