# Generated by Django 5.2.17 on 2026-08-14 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products_app', '0001_initial'),
        ('sellers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='sellers_app.sellerprofile'),
        ),
        migrations.AddIndex(
            model_name='productlisting',
            index=models.Index(fields=['status', 'published_at'], name='products_ap_status_68013c_idx'),
        ),
    ]
