# Generated by Django 5.2.17 on 2026-08-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_category_homepage_rank_productlisting_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_et',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_lt',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_lv',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='description_et',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='description_lt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='description_lv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='title_et',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='title_lt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='title_lv',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
