# Generated by Django 5.2.17 on 2026-08-20 22:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0005_backfill_default_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeroContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('title_lt', models.CharField(max_length=160, null=True)),
                ('title_lv', models.CharField(max_length=160, null=True)),
                ('title_et', models.CharField(max_length=160, null=True)),
                ('title_en', models.CharField(max_length=160, null=True)),
                ('subtitle', models.CharField(blank=True, default='', max_length=400)),
                ('subtitle_lt', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('subtitle_lv', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('subtitle_et', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('subtitle_en', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'home hero content',
            },
        ),
    ]
