# Generated by Django 5.2.17 on 2026-09-02 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0006_home_hero_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='homeherocontent',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'home hero content'},
        ),
        migrations.AlterModelOptions(
            name='productlisting',
            options={'ordering': ['-created_at']},
        ),
    ]
