# Generated by Django 5.2.17 on 2026-08-14 18:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.CharField(choices=[('dpd', 'DPD'), ('omniva', 'Omniva')], max_length=16)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('created', 'Label requested'), ('label_ready', 'Label generated'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='created', max_length=16)),
                ('label_key', models.CharField(blank=True, default='', help_text='S3 key of label PDF', max_length=255)),
                ('locker_id', models.CharField(blank=True, default='', help_text='Parcel locker code', max_length=32)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='orders_app.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('carrier_status', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField()),
                ('raw', models.JSONField(default=dict)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='shipping_app.shipment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
