# Generated by Django 5.2.17 on 2026-09-02 23:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shipment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="trackingevent",
            options={"ordering": ["-created_at"]},
        ),
        # TrackingEvent.id was created as BigAutoField in 0001_initial and the
        # model now inherits UUIDModel. A plain ALTER TYPE ... USING id::uuid
        # fails for bigint values. The table is empty in dev, so we safely drop
        # and recreate the column as uuid. For environments with data, a data
        # migration that maps old bigint IDs to new UUIDs must be run first.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="trackingevent",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE shipping_app_trackingevent
                        DROP COLUMN id;
                    ALTER TABLE shipping_app_trackingevent
                        ADD COLUMN id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL;
                    """,
                    reverse_sql="""
                    ALTER TABLE shipping_app_trackingevent
                        DROP COLUMN id;
                    ALTER TABLE shipping_app_trackingevent
                        ADD COLUMN id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY;
                    """,
                ),
            ],
        ),
    ]
