# Generated by Django 5.2.17 on 2026-08-14 18:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(help_text="e.g. 'orders.checkout', 'payments.webhook'", max_length=64)),
                ('key', models.CharField(max_length=128)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('response_status', models.PositiveIntegerField(null=True)),
                ('response_body', models.JSONField(null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope', 'key'), name='uniq_idempotency_scope_key')],
            },
        ),
    ]
