# Generated by Django 5.2.17 on 2026-09-02 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idempotencyrecord',
            options={'ordering': ['-created_at']},
        ),
    ]
