# Generated by Django 5.2.17 on 2026-08-14 18:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('LT', 'Lithuania'), ('LV', 'Latvia'), ('EE', 'Estonia')], max_length=2)),
                ('vat_number', models.CharField(blank=True, default='', help_text='Country-prefixed, e.g. LT100000000000', max_length=16)),
                ('stripe_account_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft (onboarding incomplete)'), ('submitted', 'Submitted for verification'), ('vies_pending', 'VIES validation pending'), ('verified', 'Verified (may sell)'), ('rejected', 'Rejected'), ('suspended', 'Suspended (compliance/fraud)')], default='draft', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('docs_meta', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
