# Generated by Django 5.2.17 on 2026-08-14 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='seller_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='sellerprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('vat_number', ''), _negated=True), fields=('vat_number',), name='uniq_seller_vat'),
        ),
    ]
