# Generated by Django 5.2.17 on 2026-09-02 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers_app', '0003_seller_public_storefront'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerprofile',
            options={'ordering': ['-created_at']},
        ),
    ]
