# Generated by Django 5.2.17 on 2026-08-14 18:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('checked_out', 'Checked out'), ('abandoned', 'Abandoned')], default='active', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(help_text='Human-readable, e.g. JOL-2026-000001', max_length=32, unique=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=16)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_country', models.CharField(blank=True, default='', max_length=2)),
                ('idempotency_key', models.CharField(help_text='Checkout dedupe token', max_length=128, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_snapshot', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('seller_id', models.UUIDField(help_text='Denormalized for split payouts & erasure scoping')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
