# Generated by Django 5.2.17 on 2026-08-20 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='anonymized_ref',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Irreversible pseudonymous token; set when buyer is anonymized', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(blank=True, help_text='NULL once retention anonymization has run (compliance_app.retention)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
