# Generated by Django 5.2.17 on 2026-08-22 14:36

import apps.core.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0003_order_anonymized_ref_alter_order_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_vat_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_city',
            field=apps.core.encryption.EncryptedTextField(blank=True, default='', pii_classification='indirect_identifier'),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_full_name',
            field=apps.core.encryption.EncryptedTextField(blank=True, default='', pii_classification='direct_identifier'),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_phone',
            field=apps.core.encryption.EncryptedTextField(blank=True, default='', pii_classification='contact'),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_postal_code',
            field=apps.core.encryption.EncryptedTextField(blank=True, default='', pii_classification='indirect_identifier'),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_street',
            field=apps.core.encryption.EncryptedTextField(blank=True, default='', pii_classification='direct_identifier'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_locker_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
