# Generated by Django 5.2.17 on 2026-08-20 22:09

import apps.users_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users_app.models.UserManager()),
            ],
        ),
    ]
