# Generated by Django 5.2.17 on 2026-09-02 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_audit_architecture_compliance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
    ]
