# Generated by Django 5.2.17 on 2026-08-14 18:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('seller_vat_number', models.CharField(blank=True, default='', max_length=16)),
                ('buyer_country', models.CharField(max_length=2)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reverse_charge', models.BooleanField(default=False)),
                ('pdf_key', models.CharField(blank=True, default='', help_text='S3 key of PDF', max_length=255)),
                ('issued_at', models.DateTimeField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='orders_app.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OssReturnData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(help_text='e.g. 2026Q3', max_length=7)),
                ('country', models.CharField(max_length=2)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vat_due', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(default='draft', help_text='draft|submitted|accepted', max_length=16)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('period', 'country'), name='uniq_oss_period_country')],
            },
        ),
        migrations.CreateModel(
            name='VatRateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(db_index=True, max_length=2)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Percent, e.g. 21.00', max_digits=5)),
                ('valid_from', models.DateField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('country', 'valid_from'), name='uniq_vat_country_from')],
            },
        ),
    ]
