# Generated by Django 5.2.17 on 2026-09-02 23:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tax_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ossreturndata",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="vatratesnapshot",
            options={"ordering": ["-created_at"]},
        ),
        # The initial migration created these models with BigAutoField ids.
        # The models now inherit UUIDModel, so we must convert the columns to
        # uuid. A direct ALTER TYPE ... USING id::uuid fails because PostgreSQL
        # does not allow bigint -> uuid casts.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="ossreturndata",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                migrations.AlterField(
                    model_name="vatratesnapshot",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            database_operations=[
                # OssReturnData is empty in dev: drop and recreate as uuid.
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE tax_app_ossreturndata
                        DROP COLUMN id;
                    ALTER TABLE tax_app_ossreturndata
                        ADD COLUMN id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL;
                    """,
                    reverse_sql="""
                    ALTER TABLE tax_app_ossreturndata
                        DROP COLUMN id;
                    ALTER TABLE tax_app_ossreturndata
                        ADD COLUMN id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY;
                    """,
                ),
                # VatRateSnapshot may contain data: preserve rows by adding a
                # temporary uuid column, dropping the old bigint id, and
                # renaming the new column.
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE tax_app_vatratesnapshot
                        ADD COLUMN __new_id uuid DEFAULT gen_random_uuid();
                    ALTER TABLE tax_app_vatratesnapshot
                        ALTER COLUMN __new_id DROP DEFAULT;
                    ALTER TABLE tax_app_vatratesnapshot
                        DROP CONSTRAINT tax_app_vatratesnapshot_pkey;
                    ALTER TABLE tax_app_vatratesnapshot
                        DROP COLUMN id;
                    ALTER TABLE tax_app_vatratesnapshot
                        RENAME COLUMN __new_id TO id;
                    ALTER TABLE tax_app_vatratesnapshot
                        ADD PRIMARY KEY (id);
                    ALTER TABLE tax_app_vatratesnapshot
                        ALTER COLUMN id SET DEFAULT gen_random_uuid();
                    """,
                    reverse_sql="""
                    ALTER TABLE tax_app_vatratesnapshot
                        ADD COLUMN __old_id bigint;
                    ALTER TABLE tax_app_vatratesnapshot
                        DROP CONSTRAINT tax_app_vatratesnapshot_pkey;
                    ALTER TABLE tax_app_vatratesnapshot
                        DROP COLUMN id;
                    ALTER TABLE tax_app_vatratesnapshot
                        RENAME COLUMN __old_id TO id;
                    ALTER TABLE tax_app_vatratesnapshot
                        ALTER COLUMN id SET NOT NULL;
                    ALTER TABLE tax_app_vatratesnapshot
                        ADD PRIMARY KEY (id);
                    ALTER TABLE tax_app_vatratesnapshot
                        ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
                    """,
                ),
            ],
        ),
    ]
