# Generated by Django 5.2.17 on 2026-09-02 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_app', '0002_audit_architecture_compliance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialinvoice',
            options={'ordering': ['-created_at']},
        ),
    ]
