# Generated by Django 5.2.17 on 2026-09-02 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0002_internal_payment_api'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalpaymentintent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='internalrefund',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paymentrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stripewebhookevent',
            options={'ordering': ['-created_at']},
        ),
    ]
